#!/usr/bin/env bash


# Define stderr handling
bashtrix_core__stderr() {
	if [[ $1 == '0' ]]; then
		[[ $2 ]] && printf "$2" "${@:3}" 1>&2 || :
	else
		[[ $2 ]] && printf '%s'"$2" "ERROR: ${0##*/}, " "${@:3}" 1>&2 || :
	fi
}



# JSON encode variable
bashtrix_core__json_encode_var() {
	local -n 'bashtrix_core__json_encode_var__out='"$1"
	bashtrix_core__json_encode_var__out=${bashtrix_core__json_encode_var__out//\\/\\\\}
	bashtrix_core__json_encode_var__out=${bashtrix_core__json_encode_var__out//\"/\\\"} #"
	bashtrix_core__json_encode_var__out=${bashtrix_core__json_encode_var__out//$'\n'/\\n}
}



# JSON encode pipe
bashtrix_core__json_encode_pipe() {
	sed --null-data 's/\\/\\\\/g' | \
	sed --null-data 's/"/\\"/g' | \
	sed --null-data 's/\n/\\n/g'
}



